<?php
$context["labels"] = array(
  "added_by" => "Lisatud",
  "authors" => "Autorid",
  "authors2" => "Autorid",
  "authors_clean" => "autorid",
  "categories" => "Kategooriad",
  "favorite_quotes" => "Lemmikud tsitaadid",
  "favorite_sources" => "Lemmikud allikad",
  "log_out" => "Logi välja",
  "login" => "login",
  "loginmenu" => "Login menüü",
  "profile" => "Profiil",
  "quotes" => "Tsitaadid",
  "quotes_clean" => "tsitaadid",
  "share_on_facebook" => "Jaga FaceBookois",
  "slogan" => "Eesti parim online tsitaadikogu",
  "sources_clean" => "allikad",
  "tags" => "Teemad",
  "tags_clean" => "teemad",
  "user_added_quotes" => "Kasutaja lisatud tsitaadid",
  "vote" => "Hääleta",
  "description_default" => "tsitaat.com on iga päev kasvav eesti suurim online tsitaadikogu.",
  "keywords_default" => "tsitaat tsitaadid eesti aforismid aforism",
  "page_clean" => "leht",
  "top-100-quotes_clean" => "top-100-tsitaadid",
  "search_clean" => "otsing",
  "statistics_clean" => "statistika",
  "fans_clean" => "fännid",
  "latest-quotes_clean" => "viimased-tsitaadid",
  "contributors_clean" => "panustajad",

  "favorite-quotes_clean" => "lemmikud-tsitaadid",
  "added-quotes_clean" => "lisatud-tsitaadid",

  "latest_quotations" => "Viimati lisatud tsitaadid",
  "previous_page" => "Eelmine leht",
  "page_clean" => "leht",
  "next_page" => "Järgmine leht",
  "site_title" => "Tsitaat.com - Eesti parim online tsitaadikogu",
  "was_clean" => "oli",
  
);
?>