<div class="frmrow input_text">
  <label class="frmcaption" for="input_author">Autor:</label>
  <span class="input"><input id="input_author" type="text" value="" name="author" /></span>
</div>
<div class="frmrow input_textarea">
  <label class="frmcaption" for="input_quote">Tsitaat:</label>
  <span class="input"><textarea id="input_quote" cols="60" rows="4" name="quote"></textarea></span>
</div>
<div class="frmrow input_select">
  <label class="frmcaption" for="input_category">Kategooria:</label>
  <span class="input"><select id="input_category" id="input_category" name="category" /></select></span>
</div>
<div class="frmrow input_text">
  <label class="frmcaption" for="input_tag">Teemad:</label>
  <span class="input"><input id="input_tag" type="text" value="" name="tag" /></span>
</div>
<div class="frmrow input_text">
  <label class="frmcaption" for="input_source">Allikas:</label>
  <span class="input"><input id="input_source" type="text" value="" name="source" /></span>
</div>