  <?php import('templates/header.phtml'); ?>
  <body>


    <div id="h">
    <a id="l" href="{==$baseurl=}"></a>
    <div id="s"></div>

    <ul id="n">
      <?php foreach ($nav as $item) { ?>
      <li><a href="{==$item[link]=}" <?php if ($item['class']) { ?> class="{==$item['class']=}"<?php } ?>>{==$item[name]=}</a></li>
			<?php } ?>
		</ul>
	</div>

	<div id="c">
    
    <div id="sc" class="lfloat">
			

      <ul class="i">
				<li class="title">&laquo; {==$labels['tags']=} &raquo;</li>
				<?php foreach ($tag_index as $item) { ?>
          <?php if($item == "-") { ?>
            <li><a href="{==$baseurl=}/{==$labels['quotes_clean']=}/teemad/-/" class="noUnderline<?php if($item==utf8_substr($a_path[2],0,1) && $a_path[1]=="teemad") { ?> active<?php } ?>">-</a></li>
          <?php } else { ?>
            <li><a <?php if($item==utf8_substr($a_path[2],0,1) && $a_path[1]=="teemad") { ?>class="active" <?php } ?>href="/{==$labels['quotes_clean']=}/teemad/{==$item=}/">{==$item=}</a></li>
          <?php } ?>
				<?php } ?>
			</ul>

      <ul class="i">
				<li class="title">&laquo; Autorid &raquo;</li>
				<?php foreach ($author_index as $item) { ?>
          <li><a <?php if(((strlen($a_path[2])>1&&$item==utf8_substr($a_path[2],utf8_strpos($a_path[2],"_"),1)) || (strlen($a_path[2])==1&&$item==utf8_substr($a_path[2],utf8_strpos($a_path[2],"_"),1))) && $a_path[1]=="autorid") { ?>class="active" <?php } ?>href="/{==$labels['quotes_clean']=}/autorid/{==$item=}/">{==$item=}</a></li>
				<?php } ?>
			</ul>

      <?php if(!$logged) { ?>
      <div id="login">
        <div class="title">&laquo; Login &raquo;</div>
        <form method="post" action="/foorum/ucp.php?mode=login">
          <div>
            <input type="hidden" value="{==$returnAddress=}" name="redirect" />
            <input type="hidden" value="{==$returnAddress=}" name="current_url" />
          </div>
          <div class="frmrow"><label class="textinputLogin"><span class="frmcaption">kasutaja:</span><span class="input"><input type="text" value="" name="username" /></span></label></div> 
          <div class="frmrow"><label class="textinputLogin"><span class="frmcaption">parool:</span><span class="input"><input type="password" value="" name="password" /></span></label></div> 
          <div class="frmrow">
            <input type="checkbox" name="autologin"/> <label for="autologin"></label>
          </div>
          <div class="buttonsLogin">
            <input type="submit" class="submit" value="Sign in" name="login"/>
          </div>
        </form>
      </div>
      <?php } else { ?>
      <div id="logimenu">
        <div class="title">&laquo; Loginmenüü &raquo;</div>
        <div class="item"><a class="item" href="/{==$username_clean=}">Profiil</a></div>
        <div class="item"><a class="item" href="">Lemmikud tsitaadid</a></div>
        <div class="item"><a class="item" href="">Lemmikud allikad</a></div>
        <div class="item"><a class="item" href="">Lisatud tsitaadid</a></div>
        <div class="item"><a class="item" href="/index.php?mode=logout&amp;sid={==$session_id=}&amp;redirect={==$returnAddressEncoded=}">Logi välja</a></div>
      </div>
      <?php } ?>

		</div>

    <div id="mc" class="lfloat2">
    
      <h1>{==$h1=}</h1>
			<span class="h1"><?php if ($_context['section'] == "quotes-authors-%author%" || $_context['section'] == "quotes-authors-%author%-%page%" || $_context['section'] == "quotes-authors-%author%-%quote_id%") { ?><a href="{==$baseurl=}/{==$labels['quotes_clean']=}/autorid/{==$a_path[2]=}"><?php } ?>{==$fake_h1=}<?php if ($_context['section'] == "quotes-authors-%author%" || $_context['section'] == "quotes-authors-%author%-%page%" || $_context['section'] == "quotes-authors-%author%-%quote_id%") { ?></a><?php } ?><?php if (strlen($_context['profession'])>0) { ?><span>{==$profession=}</span><?php } ?></span>

      {==$content=}

      <?php if ($section=="manage_not_active_quotations") { ?>
        
      <?php } elseif ($section=="quotes-authors-%author_index%") { ?>
        <?php import('templates/authors.phtml'); ?>
      <?php } elseif ($section=="quotes-tags-%tag_index%" && $a_path[2]!="-") { ?>
        <?php import('templates/tags.phtml'); ?>
      <?php } elseif ($section=="fans") { ?>
        <?php import('templates/fans.phtml'); ?>
      <?php } else { ?>
        <?php import('templates/quotes.phtml'); ?>
      <?php } ?>

      <?php if($navi) { ?>
			<div id="navi">
				
				<?php foreach ($navi as $item) { ?>
          <?php if($item['previous_page']) { ?>
            <a class="prev" href="{==$item['link']=}">Eelmine</a>
          <?php } elseif($item['next_page']) { ?>
            <a class="next" href="{==$item['link']=}">Järgmine</a>
          <?php } elseif($item['selected']) { ?>
          <a href="{==$item['link']=}" class="item selected">{==$item['caption']=}</a>
          <?php } else { ?>
          <a href="{==$item['link']=}" class="item">{==$item['caption']=}</a>
          <?php } ?>
				<?php } ?>
				
			</div>
			<?php } ?>



		</div>

	</div>

  <div class="clear"><!-- --></div>
  
  <?php import('templates/footer.phtml'); ?>